// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhzkDqsaBVuKc_7qfUqKZnH0ml_SdlOHc',
    appId: '1:954174929160:web:bc8f879532d28b6eecd4bd',
    messagingSenderId: '954174929160',
    projectId: 'movie-app-iti-111',
    authDomain: 'movie-app-iti-111.firebaseapp.com',
    storageBucket: 'movie-app-iti-111.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7T1hgQkD0DIazDhiAq60aGs2dAOFM2HM',
    appId: '1:954174929160:android:b4edfe14f74aa999ecd4bd',
    messagingSenderId: '954174929160',
    projectId: 'movie-app-iti-111',
    storageBucket: 'movie-app-iti-111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0bW9thLNa8r_31OA-SbxIR6hlzMkVc14',
    appId: '1:954174929160:ios:848dbcb764a763abecd4bd',
    messagingSenderId: '954174929160',
    projectId: 'movie-app-iti-111',
    storageBucket: 'movie-app-iti-111.firebasestorage.app',
    iosBundleId: 'com.example.itiMovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0bW9thLNa8r_31OA-SbxIR6hlzMkVc14',
    appId: '1:954174929160:ios:848dbcb764a763abecd4bd',
    messagingSenderId: '954174929160',
    projectId: 'movie-app-iti-111',
    storageBucket: 'movie-app-iti-111.firebasestorage.app',
    iosBundleId: 'com.example.itiMovieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhzkDqsaBVuKc_7qfUqKZnH0ml_SdlOHc',
    appId: '1:954174929160:web:2976731212e5c304ecd4bd',
    messagingSenderId: '954174929160',
    projectId: 'movie-app-iti-111',
    authDomain: 'movie-app-iti-111.firebaseapp.com',
    storageBucket: 'movie-app-iti-111.firebasestorage.app',
  );
}
